import { StyleSheet,ImageStyle,ViewStyle,TextStyle} from "react-native";

interface InitScreen{
    container:ViewStyle
    topViewContainer:ViewStyle   
    headerCitiesContainer:ViewStyle
    btnSetCities:ViewStyle
    btnSetLanguage:ViewStyle
    options:ViewStyle
    headerDisplayOptions:ViewStyle
    headerBtnActions:ViewStyle
    cardsContainer:ViewStyle
    cardDisplayOption:ViewStyle
    scrollCardsContainer:ViewStyle
}

const DashboardMainStyles : InitScreen = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        backgroundColor:'#e0e3e9',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
    },
    topViewContainer:{
        height:'14%',
        width:'100%',        
        display:'flex',
        justifyContent:'flex-end',
        alignItems:'center',
        flexDirection:'column',
        rowGap:20,
        backgroundColor:'#e0e3e9'
    },
    headerCitiesContainer:{
        height:'auto',
        width:'100%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
        columnGap:15
    },
    btnSetCities:{
        width:'auto',
        height:'auto',
        backgroundColor:'#ffffff',
        padding:5
    },
    btnSetLanguage:{
        width:'auto',
        height:'auto',
        backgroundColor:'#c6d3e6',
        padding:5
    },
    options:{
        position:'absolute',
        width:150,
        top:30,
        backgroundColor:'#ffffff',
        right:65,
        height:'auto',
        rowGap:10,
        zIndex:2,
    },
    headerDisplayOptions:{
        width:'90%',
        height:'auto',
        display:'flex',
        justifyContent:'flex-start',
        alignItems:'center',
        flexDirection:'row',
        columnGap:10
    },
    headerBtnActions:{
        width:'auto',
        height:'auto',
        padding:4,
        backgroundColor:'#c6d3e6',
        borderRadius:5
    },    
    cardsContainer:{
        height:'76%',
        width:'90%'
    },
    cardDisplayOption:{
        width:'100%',
        height:120,
        borderRadius:10,
        borderWidth:1,
        borderColor:'#000000'
    },
    scrollCardsContainer:{
        width:'100%',
        rowGap:10
    }
})

export default DashboardMainStyles