import { StyleSheet,ImageStyle,ViewStyle,TextStyle } from "react-native";

interface InitScreen{
    container:ViewStyle
    headerContainer:ViewStyle
    mainOptionsContainer:ViewStyle
    btnActionToSetInfo:ViewStyle
    textBtnAction:TextStyle
    topNavigationBar:ViewStyle
    btnBackContainer:ViewStyle
    saveBtnContainer:ViewStyle
    topNavigationBarTitle:ViewStyle
    inputContainer:ViewStyle
    inputBox:TextStyle
    inputTitle:TextStyle
    upcomingCardEvents:ViewStyle
    btnSetEvent:ViewStyle
}

const ProfileStyles : InitScreen = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'column',
        backgroundColor:'#e0e3e9'
    },
    headerContainer:{
        width:'90%',        
        height:'10%',
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between'
    },
    mainOptionsContainer:{
        width:'90%',   
        height:'80%',
        display:'flex',
        flexDirection:'column'
    },
    btnActionToSetInfo:{
        width:'100%',
        height:40,
        borderBottomWidth:1,
        borderBottomColor:'#6e8ac6',
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    textBtnAction:{
        fontSize:16,
        fontWeight:'bold'
    },
    topNavigationBar:{
        width:'100%',
        height:50,
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',       
        paddingInline:5
    },
    btnBackContainer:{
        width:'18%',
        height:'100%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
    },
    saveBtnContainer:{
        width:'18%',
        height:'100%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
    },
    topNavigationBarTitle:{
        width:'50%',
        height:'100%',
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',  
    },
    inputContainer:{
        width:'100%',
        height:40,
        borderWidth:1,
        borderColor:'#000000',
        borderRadius:10
    },
    inputBox:{
        width:'100%',
        height:'100%'
    },
    inputTitle:{
        position:'absolute',
        top:-12,
        left:6,
        backgroundColor:'#e0e3e9',
        paddingInline:4
    },
    upcomingCardEvents:{
        width:'100%',
        height:100,
        borderWidth:1,
        borderColor:'#000000',
        borderRadius:10,
        padding:5
    },
    btnSetEvent:{
        width:'100%',
        height:30,        
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
})

export default ProfileStyles